### ISSUE TITLE
SQL ROADMAP

### ISSUE THREAD

**Issue by manepullavamsi** [manepullavamsi/Tracking-issues#2]
- [ ] Complete W3 schools learning [ @](https://www.w3schools.com/sql/default.asp)
- [ ] Compelte Pratice Esay level SQL  [ @](https://platform.stratascratch.com/coding?code_type=1)
- [ ] Complete Pratice Esay level SQL problem [ @](https://datalemur.com/)
- [ ] Complete Pratice problems statements [ @](https://interview.leetcode.com/interview/login/)
